### ISSUE TITLE
Latest stable release doesn't compile on Rust 1.61

### ISSUE THREAD

**Issue by jgallagher** [mikelodder7/vsss-rs#7]
Starting a new project and adding

```toml
vsss-rs = "1.4.0"
```

to Cargo.toml will not compile with the latest version of Rust (or with Rust 1.59, which was the only other stable release I happen to have installed):

```
error[E0277]: the trait bound `Sha512: curve25519_dalek::digest::FixedOutput` is not satisfied
   --> /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/vsss-rs-1.4.0/src/curve25519.rs:339:14
    |
339 |         Self(EdwardsPoint::hash_from_bytes::<sha2::Sha512>(&seed))
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `curve25519_dalek::digest::FixedOutput` is not implemented for `Sha512`
    |
    = note: required because of the requirements on the impl of `curve25519_dalek::digest::Digest` for `Sha512`
note: required by a bound in `EdwardsPoint::hash_from_bytes`
   --> /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/curve25519-dalek-4.0.0-pre.2/src/edwards.rs:533:12
    |
533 |         D: Digest<OutputSize = U64> + Default,
    |            ^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `EdwardsPoint::hash_from_bytes`

error[E0277]: the trait bound `Sha512: HashMarker` is not satisfied
   --> /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/vsss-rs-1.4.0/src/curve25519.rs:339:14
    |
339 |         Self(EdwardsPoint::hash_from_bytes::<sha2::Sha512>(&seed))
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `HashMarker` is not implemented for `Sha512`
    |
    = note: required because of the requirements on the impl of `curve25519_dalek::digest::Digest` for `Sha512`
note: required by a bound in `EdwardsPoint::hash_from_bytes`
   --> /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/curve25519-dalek-4.0.0-pre.2/src/edwards.rs:533:12
    |
533 |         D: Digest<OutputSize = U64> + Default,
    |            ^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `EdwardsPoint::hash_from_bytes`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `vsss-rs` due to 2 previous errors
```

**Comment by mikelodder7** [comment]
Hmmm, Its working fine for my projects when I run it. Can you send your exact environment. Perhaps a docker command that can recreate the issue.

**Comment by jgallagher** [comment]
It looks like it fails in the official rust docker image:

```
bash$ docker run --rm -it rust /bin/bash
Unable to find image 'rust:latest' locally
latest: Pulling from library/rust
Digest: sha256:a2dff3d02fbe9a2d4b2ff327033245ce30f113ccbcc162600193a58c4feb1a33
Status: Downloaded newer image for rust:latest
root@77ceacbb615f:/# rustc -V
rustc 1.61.0 (fe5b13d68 2022-05-18)
root@77ceacbb615f:/# cargo -V
cargo 1.61.0 (a028ae4 2022-04-29)
root@77ceacbb615f:/# cargo new test-vsss-rs
     Created binary (application) `test-vsss-rs` package
root@77ceacbb615f:/# cd test-vsss-rs/
root@77ceacbb615f:/test-vsss-rs# cat >> Cargo.toml
vsss-rs = "1.4.0"
root@77ceacbb615f:/test-vsss-rs# cargo run
... snip ...
   Compiling typenum v1.15.0
   Compiling version_check v0.9.4
   Compiling proc-macro2 v1.0.39
   Compiling unicode-ident v1.0.0
   Compiling syn v1.0.96
   Compiling libc v0.2.126
   Compiling cfg-if v1.0.0
   Compiling subtle v2.4.1
   Compiling unicode-xid v0.2.3
   Compiling radium v0.6.2
   Compiling tap v1.0.1
   Compiling const-oid v0.6.2
   Compiling funty v1.2.0
   Compiling byteorder v1.4.3
   Compiling serde_derive v1.0.137
   Compiling serde v1.0.137
   Compiling opaque-debug v0.3.0
   Compiling cpufeatures v0.2.2
   Compiling ppv-lite86 v0.2.16
   Compiling generic-array v0.14.5
   Compiling wyz v0.4.0
   Compiling der v0.4.5
   Compiling quote v1.0.18
   Compiling bitvec v0.22.3
   Compiling spki v0.4.1
   Compiling getrandom v0.2.6
   Compiling pkcs8 v0.7.6
   Compiling rand_core v0.6.3
   Compiling rand_chacha v0.3.1
   Compiling digest v0.9.0
   Compiling crypto-mac v0.11.1
   Compiling crypto-common v0.1.3
   Compiling block-buffer v0.9.0
   Compiling signature v1.3.2
   Compiling hmac v0.11.0
   Compiling digest v0.10.3
   Compiling sha2 v0.9.9
   Compiling ff v0.10.1
   Compiling group v0.10.0
   Compiling synstructure v0.12.6
   Compiling zeroize_derive v1.3.2
   Compiling zeroize v1.3.0
   Compiling crypto-bigint v0.2.11
   Compiling curve25519-dalek v4.0.0-pre.2
   Compiling elliptic-curve v0.10.6
   Compiling ecdsa v0.12.4
   Compiling k256 v0.9.6
   Compiling serde-big-array v0.3.3
   Compiling vsss-rs v1.4.0
error[E0277]: the trait bound `Sha512: curve25519_dalek::digest::FixedOutput` is not satisfied
   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/vsss-rs-1.4.0/src/curve25519.rs:339:14
    |
339 |         Self(EdwardsPoint::hash_from_bytes::<sha2::Sha512>(&seed))
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `curve25519_dalek::digest::FixedOutput` is not implemented for `Sha512`
    |
    = note: required because of the requirements on the impl of `curve25519_dalek::digest::Digest` for `Sha512`
note: required by a bound in `EdwardsPoint::hash_from_bytes`
   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/curve25519-dalek-4.0.0-pre.2/src/edwards.rs:533:12
    |
533 |         D: Digest<OutputSize = U64> + Default,
    |            ^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `EdwardsPoint::hash_from_bytes`

error[E0277]: the trait bound `Sha512: HashMarker` is not satisfied
   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/vsss-rs-1.4.0/src/curve25519.rs:339:14
    |
339 |         Self(EdwardsPoint::hash_from_bytes::<sha2::Sha512>(&seed))
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `HashMarker` is not implemented for `Sha512`
    |
    = note: required because of the requirements on the impl of `curve25519_dalek::digest::Digest` for `Sha512`
note: required by a bound in `EdwardsPoint::hash_from_bytes`
   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/curve25519-dalek-4.0.0-pre.2/src/edwards.rs:533:12
    |
533 |         D: Digest<OutputSize = U64> + Default,
    |            ^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `EdwardsPoint::hash_from_bytes`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `vsss-rs` due to 2 previous errors
```

**Comment by mikelodder7** [comment]
This has been fixed with the 2.0.0 release
